name: markov_music
channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.11
  - pandas
  - numpy
  - seaborn
  - matplotlib
  - networkx
  - ipykernel
  - jupyter
  - fsspec
  - huggingface_hub
  - pip
  - pip:
      - music21
